breakdowns/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView 
from . import views

app_name = 'breakdowns'

urlpatterns = [
    # Index URL 
    url(r'^$', RedirectView.as_view(url='/breakdowns/my-breakdowns/'), name='index'),

    # Standard Library URL
    url(r'^library/(?P<pk>[0-9]+)/$', views.StandardLibraryDetail.as_view(), name='library_detail'),

    # Standard Library Breakdown URL
    url(r'^library/breakdown/(?P<pk>[0-9]+)/$', views.LibraryBreakdownDetail.as_view(), name='library_breakdown_detail'),

    # User Cost Breakdown List URL
    url(r'^my-breakdowns/$', views.MyBreakdownList.as_view(), name='my_breakdown_list'),

    # User Cost Breakdown Detail URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/$', views.MyBreakdownDetail.as_view(), name='my_breakdown_detail'),

    # User Cost Breakdown Create step 1 URL
    url(r'^my-breakdown/create/$', views.breakdown_create, name='breakdown_create'),

    # User Cost Breakdown Create step 2 URL
    url(r'^cost-breakdown/create/step-2$', views.step_two, name='breakdown_create_step_2'),

    # Update cost breakdown
    url(r'my-breakdown/update/(?P<pk>[0-9]+)/$', views.BreakdownUpdate.as_view(), name="breakdown_update"),

    # Delete cost breakdown
    url(r'my-breakdown/delete/(?P<pk>[0-9]+)/$', views.BreakdownDelete.as_view(), name="breakdown_delete"),

    # Create a MaterialBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/material/add/$', views.MaterialBreakdownCreate.as_view(), name='material_breakdown_create'),

    # Update a MaterialBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/material/update/(?P<pk>[0-9]+)/$', views.MaterialBreakdownUpdate.as_view(), name='material_breakdown_update'),

    # Delete a MaterialBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/material/delete/(?P<pk>[0-9]+)/$', views.MaterialBreakdownDelete.as_view(), name='material_breakdown_delete'),

    # Create a LabourBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/labour/add/$', views.LabourBreakdownCreate.as_view(), name='labour_breakdown_create'),

    # Update a LabourBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/labour/update/(?P<pk>[0-9]+)/$', views.LabourBreakdownUpdate.as_view(), name='labour_breakdown_update'),

    # Delete a LabourBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/labour/delete/(?P<pk>[0-9]+)/$', views.LabourBreakdownDelete.as_view(), name='labour_breakdown_delete'),

    # Create a EquipmentBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/equipment/add/$', views.EquipmentBreakdownCreate.as_view(), name='equipment_breakdown_create'),

    # Update a EquipmentBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/equipment/update/(?P<pk>[0-9]+)/$', views.EquipmentBreakdownUpdate.as_view(), name='equipment_breakdown_update'),

    # Delete a EquipmentBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/equipment/delete/(?P<pk>[0-9]+)/$', views.EquipmentBreakdownDelete.as_view(), name='equipment_breakdown_delete'),

    # Material List URL
    url(r'^materials/$', views.MaterialList.as_view(), name='material_list'),

    # Material Detail URL
    url(r'^material/(?P<pk>[0-9]+)/$', views.MaterialDetail.as_view(), name='material_detail'),

    # Labour List URL
    url(r'^labours/$', views.LabourPriceList.as_view(), name='labour_list'),

    # Labour Detail URL
    url(r'^labour/(?P<pk>[0-9]+)/$', views.LabourDetail.as_view(), name='labour_detail'),

    # Equipment List URL
    url(r'^equipments/$', views.EquipmentList.as_view(), name='equipment_list'),

    # Equipment Detail URL
    url(r'^equipment/(?P<pk>[0-9]+)/$', views.EquipmentDetail.as_view(), name='equipment_detail'),

    # Project List URL
    url(r'^projects/$', views.ProjectList.as_view(), name='project_list'),

    # Project Detail URL
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetail.as_view(), name='project_detail'),
    
    # Add New Project URL
    url(r'^projects/add/$', views.ProjectCreate.as_view(), name='project_create'),

    # Update Existing Project URL
    url(r'^projects/update/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='project_update'),

    # Delete Existing Project URL
    url(r'^projects/delete/(?P<pk>[0-9]+)/$', views.ProjectDelete.as_view(), name='project_delete'),
]

core/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from breakdowns import views as breakdown_views 
from django.contrib import admin

urlpatterns = [
    # Login to account URL mapper
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),

    # Logout URL mapper
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),

    # User Registration URL mapper
    url(r'^signup/$', breakdown_views.signup, name='signup'),

    # Breakdowns app urls
    url(r'^breakdowns/', include('breakdowns.urls')),

    # Redirect
    url(r'^$', RedirectView.as_view(url='/breakdowns/')),
    url(r'^admin/', admin.site.urls),
]

breakdowns/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CostBreakdown, Project, StandardLibrary

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)
    email = forms.EmailField(max_length=60)

class StepOneForm(forms.Form):
    OPTION_CHOICES = (
            ('0', 'as'),
            ('1', 'Create a new cost breakdown form scratch'),
        )
    options = forms.ChoiceField(widget=forms.RadioSelect, choices=OPTION_CHOICES)  

class StepTwoForm(forms.ModelForm):
    class Meta:
        model = CostBreakdown
        fields = ['activity_catagory', 'project', 'full_title', 'description', 'unit', 'output', 'overhead', 'profit',]

    def clean_project(self):
        data = self.cleaned_data.get('project')
        if data is None:
            raise forms.ValidationError('This field is required.')

        return data

class ChooseLibraryForm(forms.Form):
    breakdown_library = forms.ModelChoiceField(queryset=StandardLibrary.objects.all())

class CreateBreakdownForm(forms.ModelForm):
    class Meta:
        model = CostBreakdown
        fields = ['project', 'activity_catagory' ,'full_title', 'description', 'unit', 'output', 'overhead', 'profit',]

breakdowns/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import Http404, HttpResponse
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core import serializers
from datetime import date
import openpyxl
from xlrd import open_workbook
from xlwt import Workbook, easyxf, Formula
from xlutils.copy import copy
from .forms import SignupForm, StepOneForm, StepTwoForm, CreateBreakdownForm, ChooseLibraryForm
from .models import Package, UserMembership, City, ProjectCatagory, Project, UnitCatagory, Unit, MaterialCatagory, Material, MaterialPrice, LabourCatagory, Labour, LabourPrice, EquipmentCatagory, Equipment, ActivityCatagory, CostBreakdown, MaterialBreakdown, LabourBreakdown, EquipmentBreakdown, StandardLibrary, LibraryBreakdown

# Create your views here.
@login_required
def index(request):
    # current_membership = list(UserMembership.objects.filter(user=request.user).filter(approved=True).filter(is_expired=False).order_by('-package')[0])
    # request.session['account'] = serializers.serialize('json', current_membership)

    return render(request, 'breakdowns/index.html', context={
            'page_name': 'Index',
        })

# Signup view
def signup(request):
    """
    Register a new user, login the new user and redirect to breakdowns:index page
    """
    # Check if user already logged
    if request.user.is_authenticated:
        return redirect('breakdowns:index')
        
    form_class = SignupForm
    template_name = 'registration/signup.html'

    if request.method == 'POST':
        form = form_class(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            form.save()
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            # member_group = Group.objects.get(name='member')
            # user.groups.add(member_group,)
            user.save()

            # Register new user to default account package
            # default_package = Package.objects.get(default=True)
            # membership = UserMembership(user=user, package=default_package)
            # membership.save()

            # Login and redirect to user dashboard
            login(request, user)
            return redirect('breakdowns:index')
    else:
        form = form_class()
    return render(request, template_name, context={'form': form})

# Material List View
class MaterialList(LoginRequiredMixin, generic.ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        return Material.objects.filter(created_by__is_staff=True)

    def get_context_data(self, *args, **kwargs):
        context = super(MaterialList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = MaterialCatagory.objects.all().count()
        context['page_name'] = 'materials'
        return context  

# Material Detail View
class MaterialDetail(LoginRequiredMixin, generic.DetailView):
    model = Material

    def get_context_data(self, *args, **kwargs):
        context = super(MaterialDetail, self).get_context_data(*args, **kwargs)
        context['price_list'] = MaterialPrice.objects.filter(material_id=self.kwargs['pk'])
        context['page_name'] = 'materials'
        return context

# Labour List View
class LabourPriceList(LoginRequiredMixin, generic.ListView):
    model = LabourPrice
    template_name = 'breakdowns/labour_list.html'
    context_object_name = 'labour_price_list'

    def get_queryset(self, *args, **kwargs):
        # return LabourPrice.objects.filter(created_by__is_staff=True)
        return LabourPrice.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(LabourPriceList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = LabourCatagory.objects.all().count()
        context['city_count'] = City.objects.all().count()
        context['page_name'] = 'labour'
        return context  

# Labour Detail View
class LabourDetail(LoginRequiredMixin, generic.DetailView):
    model = Labour

    def get_context_data(self, *args, **kwargs):
        context = super(LabourDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'labour'
        return context

# Equipment List View
class EquipmentList(LoginRequiredMixin, generic.ListView):
    model = Equipment

    def get_queryset(self, *args, **kwargs):
        return Equipment.objects.filter(created_by__is_staff=True)

    def get_context_data(self, *args, **kwargs):
        context = super(EquipmentList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = EquipmentCatagory.objects.all().count()
        context['page_name'] = 'equipment'
        return context 

# Equipment Detail View
class EquipmentDetail(LoginRequiredMixin, generic.DetailView):
    model = Equipment

    def get_context_data(self, *args, **kwargs):
        context = super(EquipmentDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Equipments'
        return context

# Project List View
class ProjectList(LoginRequiredMixin, generic.ListView):
    model = Project

    def get_queryset(self, *args, **kwargs):
        return Project.objects.filter(created_by=self.request.user.id)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = ProjectCatagory.objects.all().count()
        context['page_name'] = 'Projects'
        return context

# Project Detail View
class ProjectDetail(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Project
    login_url = 'breakdowns:project_list'
    redirect_field_name = None

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        return project.created_by.id == self.request.user.id

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context

# Project Create View
class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['full_title', 'short_title', 'city', 'client', 'consultant', 'contractor', 'project_catagory',]
    success_url = '/breakdowns/projects/'
    redirect_field_name = None
    
    def form_valid(self, form, *args, **kwargs):
        form.instance.created_by = self.request.user 
        return super(ProjectCreate, self).form_valid(form, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectCreate, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = ProjectCatagory.objects.all();
        context['page_name'] = 'Projects'
        return context

# Project Update View
class ProjectUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['full_title', 'short_title', 'city', 'client', 'consultant', 'contractor', 'project_catagory',]
    login_url = 'breakdowns:project_list'
    success_url = '/breakdowns/projects/'
    redirect_field_name = None

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        return project.created_by.id == self.request.user.id

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectUpdate, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = ProjectCatagory.objects.all();
        context['page_name'] = 'Projects'
        return context

# Project Delete View
class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'breakdowns/project_form.html'
    success_url = reverse_lazy('breakdowns:project_list')

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDelete, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context

# Standard Library Detail 
class StandardLibraryDetail(LoginRequiredMixin, generic.DetailView):
    model = StandardLibrary
    context_object_name = 'library'
    template_name = 'breakdowns/library_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(StandardLibraryDetail, self).get_context_data(*args, **kwargs)
        context['breakdown_list'] = LibraryBreakdown.objects.filter(standard_library=self.kwargs['pk'])
        context['page_name'] = 'library'
        context['subpage_name'] = self.object.full_title 
        return context

# Standard Library Breakdown Detail
class LibraryBreakdownDetail(LoginRequiredMixin, generic.DetailView):
    model = LibraryBreakdown
    context_object_name = 'library_breakdown'
    template_name = 'breakdowns/library_breakdown_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(LibraryBreakdownDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'library'
        context['subpage_name'] = self.object.standard_library.full_title
        return context

# All My Cost breakdowns list
class MyBreakdownList(LoginRequiredMixin, generic.ListView):
    model = CostBreakdown
    template_name = 'breakdowns/my_breakdown_list.html'
    context_object_name = 'cost_breakdown_list'
    login_url = 'breakdowns:my_breakdown_list'

breakdowns/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <!-- PAGE TITLE -->
    {% block title %}
    <title>Orit Cost Breakdowns</title>
    {% endblock title %}

    <meta name="author" content="Eyob Tariku <eyobtariku@gmail.com>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     
     <!-- PAGE DESCRIPTION -->
    {% block description %}
    <meta name="description" content="">
    {% endblock description %}

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- FONT-AWESOME -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">

    <!-- BOOTSTRAP SELECT -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}">

    <!-- NAVBAR-FIXED-SIDE -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar-fixed-side.css' %}">

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">
    
    <!-- DEFAULT STYLE -->
    {% block default_style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
    {% endblock default_style %}

    <!-- MAIN STYLE -->
    {% block main_style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock main_style %}

    <!-- PAGE STYLE -->
    {% block page_style %}
    {% endblock page_style %}
</head>
<body>
    {% block wrapper %}
    <div id="account-wrapper">
        <div class="container">
            <div class="row">
                
                <!-- PAGE NAVIGATION -->
                {% block page_nav %}
                <section class="col-sm-2 account-left-col height-lg" id="account-col">
                    <div id="account-container" class="section-container navbar-fixed-side">
                        <h2 class="h4"><a id="account-brand" href="{% url 'breakdowns:index' %}"><span class="fa fa-fire"></span> Orit Breakdowns</a></h2>

                        <nav id="side-nav">
                            <ul class="list-unstyled">
                                <li {% if page_name == 'Index' %} class="active" {% endif %}>
                                    <a href="{% url 'breakdowns:index' %}"><span class="fa fa-home"></span>&nbsp; Home</a>
                                </li>
                                
                                {% if not perms.breakdowns.manage_library %}
                                <li {% if page_name == 'CostBreakdowns' %} class="active" {% endif %}>
                                    <a href="{% url 'breakdowns:my_breakdown_list' %}"><span class="fa fa-file-o"></span>&nbsp; Cost Breakdowns</a>
                                    {% if page_name == 'CostBreakdowns' %}
                                    <ul class="list-unstyled secondary-menu">
                                        <li {% if subpage_name == 'mybreakdowns' %} class="active" {% endif %}>
                                            <a href="{% url 'breakdowns:my_breakdown_list' %}"><span class="fa fa-angle-right"></span>&nbsp; My Breakdowns</a>
                                        </li>
                                        
                                        <li {% if subpage_name == 'add' %} class="active" {% endif %}>
                                            <a href="{% url 'breakdowns:breakdown_create_step_1' %}"><span class="fa fa-angle-right"></span>&nbsp; Add New</a>
                                        </li>

                                    </ul>
                                    {% endif %}
                                </li>
                                {% endif %}

                                <li {% if page_name == 'library' %} class="active" {% endif %}>
                                    <a href="#"><span class="fa fa-archive"></span>&nbsp; Standard Library</a>
                                    {% if page_name == 'library' and perms.breakdowns.manage_library %}
                                    <ul class="list-unstyled secondary-menu">
                                        <li {% if subpage_name == 'add' %} class="active" {% endif %}>
                                            <a href="{% url 'breakdowns:breakdown_create_step_1' %}"><span class="fa fa-angle-right"></span>&nbsp; Add New</a>
                                        </li>
                                    </ul>
                                    {% endif %}
                                </li>

                                <li {% if page_name == 'Materials' %}class="active"{% endif %}>
                                    <a href="{% url 'breakdowns:material_list' %}"><span class="fa fa-cube"></span>&nbsp; Material Library</a>
                                </li>

                                <li {% if page_name == 'Labours' %}class="active"{% endif %}>
                                    <a href="{% url 'breakdowns:labour_list' %}"><span class="fa fa-child"></span>&nbsp; Labour Library</a>
                                </li>

                                <li {% if page_name == 'Equipments' %}class="active"{% endif %}>
                                    <a href="{% url 'breakdowns:equipment_list' %}"><span class="fa fa-wrench"></span>&nbsp; Equipment Library</a>
                                </li>

                                <li {% if page_name == 'Projects' %}class="active"{% endif %}>
                                    <a href="{% url 'breakdowns:project_list' %}"><span class="fa fa-database"></span>&nbsp; Projects</a>
                                    {% if page_name == 'Projects' %}
                                    <ul class="list-unstyled secondary-menu">
                                        <li {% if subpage_name == 'Add' %} class="active" {% endif %}>
                                            <a href="{% url 'breakdowns:project_create' %}"><span class="fa fa-angle-right"></span>&nbsp; Add</a>
                                        </li>
                                    </ul>
                                    {% endif %}
                                </li>

                                <li><a href="#"><span class="fa fa-bookmark"></span>&nbsp; Tutorial</a></li>
                                <li><a href="#"><span class="fa fa-book"></span>&nbsp; Documentation</a></li>
                                <li><a href="#"><span class="fa fa-user"></span>&nbsp; Profile</a></li>
                                <li><a href="#"><span class="fa fa-sliders"></span>&nbsp; Settings</a></li>
                            </ul>
                        </nav>
                    </div><!-- /.account-container -->
                </section><!-- /#account-nav -->
                {% endblock page_nav %}<!-- /END PAGE NAVIGATION -->
                
                <!-- PAGE MAIN CONTENT -->
                {% block right-col %}
                <section class="col-sm-10 account-right-col height-lg">

                    <!-- HEADER -->
                    {% block header %}
                    <header id="account-header">
                        <nav class="navbar navbar-default">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                                       <span class="sr-only">Toggle navigation</span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                 </button>
                            </div><!-- /.navbar-header -->

                            <div class="collapse navbar-collapse" id="menu">
                                <form class="navbar-form navbar-left" name="search_form" action="#">
                                    <div class="form-group">
                                        <div class="input-group input-group-sm">
                                            <input type="search" class="form-control" id="global-search-input" name="global_search" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-default">
                                                    <span class="fa fa-search"></span>
                                                </button>
                                            </span>
                                        </div><!-- /.input-group -->                                    
                                    </div><!-- /.form-group -->
                                </form>

                                <ul class="nav navbar-nav navbar-right">
                                    <li class="bold"><a href="#"><span class="fa fa-user" aria-hidden="true"></span>&nbsp; {% if user.get_full_name %}{{ user.get_full_name|title }}{% else %}{{ user.get_username|capfirst }}{% endif %}</a></li>
                                    <li class="bold"><a href="{% url 'logout' %}">Logout <span class="fa fa-sign-out"></span></a></li>
                                </ul>
                            </div><!-- /#menu -->
                        </nav>
                    </header><!-- /#account-header -->
                    {% endblock header %}
                    
                    {% block main %}
                    <main role="main" id="main">
                        <article id="account-main-article">
                            {% block content %}
                            {% endblock content %}
                        </article>
                    </main>
                    {% endblock main %}
                </section><!-- /.account-right-col -->
                {% endblock right-col %}
            </div><!-- /.row -->    
            
            {% block footer %}
            <footer id="page-footer">
                {% block footer-content %}
                <ul class="list-inline text-center">
                    <li class="small"><a href="#"><span class="fa fa-envelope"></span></a></li>
                    <li class="small"><a href="#"><span class="fa fa-facebook"></span></a></li>
                    <li class="small"><a href="#"><span class="fa fa-twitter"></span></a></li>
                    <li class="small"><a href="#"><span class="fa fa-whatsapp"></span></a></li>
                    <li class="small"><a href="#"><span class="fa fa-linkedin"></span></a></li> | 
                    <li class="small">Copyright &copy; {% now 'Y' %}. All Rights Reserved.</li>
                </ul>
                {% endblock footer-content %}
            </footer><!-- /#page-footer -->
            {% endblock footer %}
        </div><!-- /.container -->
    </div><!-- /#account-wrapper -->
    {% endblock wrapper %}
    

<!-- JQUERY -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- BOOTSTRAP SCRIPT -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- BOOTSTRAP SELECT SCRIPT -->
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>

<!-- MAIN SCRIPT -->
{% block main_script %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock main_script %}

<!-- PAGE SCRIPT -->
{% block page_script %}
{% endblock page_script %}
</body>
</html>