breakdowns/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView 
from . import views

app_name = 'breakdowns'

urlpatterns = [
    # Index URL 
    url(r'^$', RedirectView.as_view(url='/breakdowns/my-breakdowns/'), name='index'),

    # Standard Library URL
    url(r'^library/(?P<pk>[0-9]+)/$', views.StandardLibraryDetail.as_view(), name='library_detail'),

    # Standard Library Breakdown URL
    url(r'^library/breakdown/(?P<pk>[0-9]+)/$', views.LibraryBreakdownDetail.as_view(), name='library_breakdown_detail'),

    # User Cost Breakdown List URL
    url(r'^my-breakdowns/$', views.MyBreakdownList.as_view(), name='my_breakdown_list'),

    # User Cost Breakdown Detail URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/$', views.MyBreakdownDetail.as_view(), name='my_breakdown_detail'),

    # User Cost Breakdown Create step 1 URL
    url(r'^my-breakdown/create/$', views.breakdown_create, name='breakdown_create'),

    # User Cost Breakdown Create step 2 URL
    url(r'^cost-breakdown/create/step-2$', views.step_two, name='breakdown_create_step_2'),

    # Update cost breakdown
    url(r'my-breakdown/update/(?P<pk>[0-9]+)/$', views.BreakdownUpdate.as_view(), name="breakdown_update"),

    # Delete cost breakdown
    url(r'my-breakdown/delete/(?P<pk>[0-9]+)/$', views.BreakdownDelete.as_view(), name="breakdown_delete"),

    # Create a MaterialBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/material/add/$', views.MaterialBreakdownCreate.as_view(), name='material_breakdown_create'),

    # Update a MaterialBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/material/update/(?P<pk>[0-9]+)/$', views.MaterialBreakdownUpdate.as_view(), name='material_breakdown_update'),

    # Delete a MaterialBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/material/delete/(?P<pk>[0-9]+)/$', views.MaterialBreakdownDelete.as_view(), name='material_breakdown_delete'),

    # Create a LabourBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/labour/add/$', views.LabourBreakdownCreate.as_view(), name='labour_breakdown_create'),

    # Update a LabourBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/labour/update/(?P<pk>[0-9]+)/$', views.LabourBreakdownUpdate.as_view(), name='labour_breakdown_update'),

    # Delete a LabourBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/labour/delete/(?P<pk>[0-9]+)/$', views.LabourBreakdownDelete.as_view(), name='labour_breakdown_delete'),

    # Create a EquipmentBreakdown for Breakdown URL
    url(r'^my-breakdown/(?P<pk>[0-9]+)/equipment/add/$', views.EquipmentBreakdownCreate.as_view(), name='equipment_breakdown_create'),

    # Update a EquipmentBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/equipment/update/(?P<pk>[0-9]+)/$', views.EquipmentBreakdownUpdate.as_view(), name='equipment_breakdown_update'),

    # Delete a EquipmentBreakdown for a Particular Breakdown URL
    url(r'^my-breakdown/(?P<breakdown_pk>[0-9]+)/equipment/delete/(?P<pk>[0-9]+)/$', views.EquipmentBreakdownDelete.as_view(), name='equipment_breakdown_delete'),

    # Material List URL
    url(r'^materials/$', views.MaterialList.as_view(), name='material_list'),

    # Material Detail URL
    url(r'^material/(?P<pk>[0-9]+)/$', views.MaterialDetail.as_view(), name='material_detail'),

    # Labour List URL
    url(r'^labours/$', views.LabourPriceList.as_view(), name='labour_list'),

    # Labour Detail URL
    url(r'^labour/(?P<pk>[0-9]+)/$', views.LabourDetail.as_view(), name='labour_detail'),

    # Equipment List URL
    url(r'^equipments/$', views.EquipmentList.as_view(), name='equipment_list'),

    # Equipment Detail URL
    url(r'^equipment/(?P<pk>[0-9]+)/$', views.EquipmentDetail.as_view(), name='equipment_detail'),

    # Project List URL
    url(r'^projects/$', views.ProjectList.as_view(), name='project_list'),

    # Project Detail URL
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetail.as_view(), name='project_detail'),
    
    # Add New Project URL
    url(r'^projects/add/$', views.ProjectCreate.as_view(), name='project_create'),

    # Update Existing Project URL
    url(r'^projects/update/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='project_update'),

    # Delete Existing Project URL
    url(r'^projects/delete/(?P<pk>[0-9]+)/$', views.ProjectDelete.as_view(), name='project_delete'),
]

core/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from breakdowns import views as breakdown_views 
from django.contrib import admin

urlpatterns = [
    # Login to account URL mapper
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),

    # Logout URL mapper
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),

    # User Registration URL mapper
    url(r'^signup/$', breakdown_views.signup, name='signup'),

    # Breakdowns app urls
    url(r'^breakdowns/', include('breakdowns.urls')),

    # Redirect
    url(r'^$', RedirectView.as_view(url='/breakdowns/')),
    url(r'^admin/', admin.site.urls),
]

breakdowns/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CostBreakdown, Project, StandardLibrary

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)
    email = forms.EmailField(max_length=60)

class StepOneForm(forms.Form):
    OPTION_CHOICES = (
            ('0', 'as'),
            ('1', 'Create a new cost breakdown form scratch'),
        )
    options = forms.ChoiceField(widget=forms.RadioSelect, choices=OPTION_CHOICES)  

class StepTwoForm(forms.ModelForm):
    class Meta:
        model = CostBreakdown
        fields = ['activity_catagory', 'project', 'full_title', 'description', 'unit', 'output', 'overhead', 'profit',]

    def clean_project(self):
        data = self.cleaned_data.get('project')
        if data is None:
            raise forms.ValidationError('This field is required.')

        return data

class ChooseLibraryForm(forms.Form):
    breakdown_library = forms.ModelChoiceField(queryset=StandardLibrary.objects.all())

class CreateBreakdownForm(forms.ModelForm):
    class Meta:
        model = CostBreakdown
        fields = ['project', 'activity_catagory' ,'full_title', 'description', 'unit', 'output', 'overhead', 'profit',]

breakdowns/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import Http404, HttpResponse
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core import serializers
from datetime import date
import openpyxl
from xlrd import open_workbook
from xlwt import Workbook, easyxf, Formula
from xlutils.copy import copy
from .forms import SignupForm, StepOneForm, StepTwoForm, CreateBreakdownForm, ChooseLibraryForm
from .models import Package, UserMembership, City, ProjectCatagory, Project, UnitCatagory, Unit, MaterialCatagory, Material, MaterialPrice, LabourCatagory, Labour, LabourPrice, EquipmentCatagory, Equipment, ActivityCatagory, CostBreakdown, MaterialBreakdown, LabourBreakdown, EquipmentBreakdown, StandardLibrary, LibraryBreakdown

# Create your views here.
@login_required
def index(request):
    # current_membership = list(UserMembership.objects.filter(user=request.user).filter(approved=True).filter(is_expired=False).order_by('-package')[0])
    # request.session['account'] = serializers.serialize('json', current_membership)

    return render(request, 'breakdowns/index.html', context={
            'page_name': 'Index',
        })

# Signup view
def signup(request):
    """
    Register a new user, login the new user and redirect to breakdowns:index page
    """
    # Check if user already logged
    if request.user.is_authenticated:
        return redirect('breakdowns:index')
        
    form_class = SignupForm
    template_name = 'registration/signup.html'

    if request.method == 'POST':
        form = form_class(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            form.save()
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            # member_group = Group.objects.get(name='member')
            # user.groups.add(member_group,)
            user.save()

            # Register new user to default account package
            # default_package = Package.objects.get(default=True)
            # membership = UserMembership(user=user, package=default_package)
            # membership.save()

            # Login and redirect to user dashboard
            login(request, user)
            return redirect('breakdowns:index')
    else:
        form = form_class()
    return render(request, template_name, context={'form': form})

# Material List View
class MaterialList(LoginRequiredMixin, generic.ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        return Material.objects.filter(created_by__is_staff=True)

    def get_context_data(self, *args, **kwargs):
        context = super(MaterialList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = MaterialCatagory.objects.all().count()
        context['page_name'] = 'materials'
        return context  

# Material Detail View
class MaterialDetail(LoginRequiredMixin, generic.DetailView):
    model = Material

    def get_context_data(self, *args, **kwargs):
        context = super(MaterialDetail, self).get_context_data(*args, **kwargs)
        context['price_list'] = MaterialPrice.objects.filter(material_id=self.kwargs['pk'])
        context['page_name'] = 'materials'
        return context

# Labour List View
class LabourPriceList(LoginRequiredMixin, generic.ListView):
    model = LabourPrice
    template_name = 'breakdowns/labour_list.html'
    context_object_name = 'labour_price_list'

    def get_queryset(self, *args, **kwargs):
        # return LabourPrice.objects.filter(created_by__is_staff=True)
        return LabourPrice.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(LabourPriceList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = LabourCatagory.objects.all().count()
        context['city_count'] = City.objects.all().count()
        context['page_name'] = 'labour'
        return context  

# Labour Detail View
class LabourDetail(LoginRequiredMixin, generic.DetailView):
    model = Labour

    def get_context_data(self, *args, **kwargs):
        context = super(LabourDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'labour'
        return context

# Equipment List View
class EquipmentList(LoginRequiredMixin, generic.ListView):
    model = Equipment

    def get_queryset(self, *args, **kwargs):
        return Equipment.objects.filter(created_by__is_staff=True)

    def get_context_data(self, *args, **kwargs):
        context = super(EquipmentList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = EquipmentCatagory.objects.all().count()
        context['page_name'] = 'equipment'
        return context 

# Equipment Detail View
class EquipmentDetail(LoginRequiredMixin, generic.DetailView):
    model = Equipment

    def get_context_data(self, *args, **kwargs):
        context = super(EquipmentDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Equipments'
        return context

# Project List View
class ProjectList(LoginRequiredMixin, generic.ListView):
    model = Project

    def get_queryset(self, *args, **kwargs):
        return Project.objects.filter(created_by=self.request.user.id)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectList, self).get_context_data(*args, **kwargs)
        context['catagory_count'] = ProjectCatagory.objects.all().count()
        context['page_name'] = 'Projects'
        return context

# Project Detail View
class ProjectDetail(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Project
    login_url = 'breakdowns:project_list'
    redirect_field_name = None

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        return project.created_by.id == self.request.user.id

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context

# Project Create View
class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['full_title', 'short_title', 'city', 'client', 'consultant', 'contractor', 'project_catagory',]
    success_url = '/breakdowns/projects/'
    redirect_field_name = None
    
    def form_valid(self, form, *args, **kwargs):
        form.instance.created_by = self.request.user 
        return super(ProjectCreate, self).form_valid(form, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectCreate, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = ProjectCatagory.objects.all();
        context['page_name'] = 'Projects'
        return context

# Project Update View
class ProjectUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['full_title', 'short_title', 'city', 'client', 'consultant', 'contractor', 'project_catagory',]
    login_url = 'breakdowns:project_list'
    success_url = '/breakdowns/projects/'
    redirect_field_name = None

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        return project.created_by.id == self.request.user.id

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectUpdate, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = ProjectCatagory.objects.all();
        context['page_name'] = 'Projects'
        return context

# Project Delete View
class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'breakdowns/project_form.html'
    success_url = reverse_lazy('breakdowns:project_list')

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDelete, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context

# Standard Library Detail 
class StandardLibraryDetail(LoginRequiredMixin, generic.DetailView):
    model = StandardLibrary
    context_object_name = 'library'
    template_name = 'breakdowns/library_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(StandardLibraryDetail, self).get_context_data(*args, **kwargs)
        context['breakdown_list'] = LibraryBreakdown.objects.filter(standard_library=self.kwargs['pk'])
        context['page_name'] = 'library'
        context['subpage_name'] = self.object.full_title 
        return context

# Standard Library Breakdown Detail
class LibraryBreakdownDetail(LoginRequiredMixin, generic.DetailView):
    model = LibraryBreakdown
    context_object_name = 'library_breakdown'
    template_name = 'breakdowns/library_breakdown_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(LibraryBreakdownDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'library'
        context['subpage_name'] = self.object.standard_library.full_title
        return context

# All My Cost breakdowns list
class MyBreakdownList(LoginRequiredMixin, generic.ListView):
    model = CostBreakdown
    template_name = 'breakdowns/my_breakdown_list.html'
    context_object_name = 'cost_breakdown_list'
    login_url = 'breakdowns:my_breakdown_list'

breakdowns/templates/breakdowns/breakdown_form_update.html
{% extends 'base.html' %}

{% block title %}
<title>Update Cost Breakdown | Orit</title>
{% endblock %}

{% block content %}
<div class="panel panel-default panel-detail" id="material-detail-panel">
    <div class="panel-heading">
      Update Cost Breakdown
    </div><!-- /END .panel-heading -->

    <div class="panel-body">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-1 breath-up-sm">
                <form name="project_form" id="create-project-form" class="form-horizontal" method="POST">
                {% csrf_token %}

                    {{ form.non_field_errors }}
                    <fieldset id="breakdown-meta">
                        <!--- PROJECT TITLE -->
                        {% if not perms.breakdowns.manage_library %}
                        <div class="form-group">
                            <label for="project" class="col-sm-4 control-label">Project</label>
                            <div class="col-sm-8">
                                <select name="project" class="selectpicker" data-width="100%" data-live-search="true" title="Select A Project">
                                    {% for project in project_list %}
                                    <option value="{{ project.id }}" {% if project.id == form.project.value|add:0 %} selected="selected" {% endif%}>
                                        {{ project }}
                                    </option>
                                    {% endfor %}
                                </select>

                                <div class="errorlist-container">
                                    {{ form.project.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        {% endif %}
                        
                        <!-- COST BREAKDOWN CATAGORY -->
                        <div class="form-group">
                            <label for="catagory" class="col-sm-4 control-label">Catagory</label>
                            <div class="col-sm-8">
                                <select name="cost_breakdown_catagory" class="selectpicker" data-width="100%" title="Choose a Catagory" data-live-search="true">
                                     {% for catagory in catagory_list %}
                                         <option value="{{ catagory.id }}" 
                                             {% if catagory.id == form.cost_breakdown_catagory.value|add:0 %} 
                                                selected="selected"
                                             {% elif catagory.id == costbreakdown.cost_breakdown_catagory.id %}
                                                selected="selected"
                                             {% endif%}>
                                             {{ catagory|title }}
                                         </option>
                                     {% endfor %}
                                </select>

                                <div class="errorlist-container">
                                    {{ form.cost_breakdown_catagory.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        
                        <!-- COST BREAKDOWN TITLE -->
                        <div class="form-group">
                            <label for="full-title" class="col-sm-4 control-label">Title</label>
                            <div class="col-sm-8">
                                <input type="text" name="full_title" id="full-title" class="form-control"
                                {% if form.full_title.value %}
                                 value="{{ form.full_title.value|default_if_none:'' }}"
                                {% elif costbreakdown.full_title %}
                                 value="{{ costbreakdown.full_title|default_if_none:'' }}"
                                {% endif %}>
                                <div class="errorlist-container">
                                    {{ form.full_title.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        
                        <!-- COST BREAKDOWN DESCRIPTION/SUMMARY -->
                        <div class="form-group">
                            <label for="description" class="col-sm-4 control-label">Summary</label>
                            <div class="col-sm-8">
                                <textarea name="description" id="description"class="form-control" rows="5"> {% if form.description.value %}{{ form.description.value|default_if_none:'' }}{% elif costbreakdown.description %}{{ costbreakdown.description|default_if_none:'' }}
                                {% endif %}</textarea>
                                <div class="errorlist-container">
                                    {{ form.description.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->

                        <!-- MEASUREMENT UNIT -->
                        <div class="form-group">
                            <label for="unit" class="col-sm-4 control-label">Measurment Unit</label>
                            <div class="col-sm-8">
                                <select name="unit" class="selectpicker " data-live-search="true" title="Choose Measurement Unit" data-width="100%">
                                    {% for unit_catagory in unit_catagory_list %}
                                    <optgroup label="{{ unit_catagory.full_title }}">
                                        {% for unit in unit_catagory.unit_set.all %}
                                        <option value="{{ unit.id }}" 
                                            {% if unit.id == form.unit.value|add:0 %} 
                                               selected="selected"
                                            {% elif unit.id == costbreakdown.unit.id %}
                                               selected="selected"
                                            {% endif%}>
                                            {{ unit.full_title }} ({{ unit.short_title }})
                                        </option>
                                        {% endfor %}
                                    </optgroup>
                                    {% endfor %}
                                </select>
                                <div class="errorlist-container">
                                    {{ form.unit.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->

                        {% if costbreakdown.unit %}
                        <input type="hidden" name="unit" value="{{ costbreakdown.unit.id }}">
                        {% endif %}
                        
                        <!-- HOURLY OUTPUT -->
                        <div class="form-group">
                            <label for="output" class="col-sm-4 control-label">Hourly Output</label>
                            <div class="col-sm-8">
                                <input type="text" name="output" id="output" class="form-control"
                                {% if form.output.value %}
                                 value="{{ form.output.value|default_if_none:'' }}"
                                {% elif costbreakdown.output %}
                                 value="{{ costbreakdown.output|default_if_none:'' }}"
                                {% endif %}>
                                <div class="errorlist-container">
                                    {{ form.output.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        
                        <!-- OVERHEAD -->
                        {% if not user.is_staff %}
                        <div class="form-group">
                            <label for="overhead" class="col-sm-4 control-label">Overhead(%)</label>
                            <div class="col-sm-8">
                                <input type="text" name="overhead" id="overhead" class="form-control"
                                {% if form.overhead.value %}
                                 value="{{ form.overhead.value|default_if_none:'' }}"
                                {% elif costbreakdown.overhead %}
                                 value="{{ costbreakdown.overhead }}"
                                {% else %}
                                value="0.00"
                                {% endif %}>
                                <div class="errorlist-container">
                                    {{ form.overhead.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        
                        <!-- PROFIT -->
                        <div class="form-group">
                            <label for="profit" class="col-sm-4 control-label">Profit(%)</label>
                            <div class="col-sm-8">
                                <input type="text" name="profit" id="profit" class="form-control"
                                {% if form.profit.value %}
                                 value="{{ form.profit.value|default_if_none:'' }}"
                                {% elif costbreakdown.profit %}
                                 value="{{ costbreakdown.profit }}"
                                {% else %}
                                value="0.00"
                                {% endif %}>
                                <div class="errorlist-container">
                                    {{ form.profit.errors }}
                                </div>
                            </div>
                        </div><!-- /.form-group -->
                        {% endif %}                      
                    </fieldset>

                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4">
                            <div class="form-group pad-left-sm pad-up-sm">
                                <a href="{% url 'breakdowns:breakdown_delete' costbreakdown.id %}" class="btn btn-danger">Delete</a>&nbsp;
                            </div><!-- /.form-group -->
                        </div><!-- /.col-sm-4 -->

                        <div class="col-sm-4">
                            <div class="pad-up-sm text-right">
                                <a href="{% url 'breakdowns:my_breakdown_detail' costbreakdown.id %}" class="btn btn-default">Cancel</a>&nbsp;
                                <input type="submit" class="btn btn-primary" value="Update">&nbsp;
                            </div>
                        </div>
                    </div><!-- /.row -->                
                </form>
            </div><!-- /.col-sm-6 -->
        </div><!-- /.row -->
    </div><!-- /.panel-body -->
</div><!-- /END .material-detail-panel -->
{% endblock content %}

breakdowns/templates/breakdowns/project_list.html
{% extends 'base2.html' %}
{% load humanize %}

{% block title %}
<title>My Projects | Orit</title>
{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="view-header">
                <div class="pull-right text-right" style="line-height: 14px">
                    <small>Luna Admin Theme<br>Dashboard<br> <span class="c-white">v.1.3</span></small>
                </div>
                <div class="header-icon">
                    <i class="pe page-header-icon pe-7s-calculator"></i>
                </div>
                <div class="header-title">
                    <h3 class="m-b-xs">My Projects</h3>
                    <small>
                        Special minimal admin theme with Dark UI style for monitoring or administration web applications.
                    </small>
                </div>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-filled">
                <div class="panel-heading">
                    Complete list of all my construction projects
                </div>
                <div class="panel-body">
                   {% if project_list %}
                   <div class="table-responsive">
                       <table class="project-table table data-table table-hover table-striped">
                           <thead>
                               <tr>
                                   <th>#</th>
                                   <th>Project</th>
                                   <th>Catagory</th>
                                   <th>Last Updated</th>
                                   <th class="text-right">Actions</th>
                               </tr>
                           </thead>

                           <tbody>
                               {% for project in project_list %}
                               <tr>
                                   <td>{{ forloop.counter }}</td>
                                   <td><a href="{% url 'breakdowns:project_update' project.id %}">{% if project.short_title %}
                                       {{ project.short_title }}
                                     {% else %}
                                       {{ project.full_title }}
                                     {% endif %}
                                   </a></td>
                                   <td>{{ project.project_catagory.full_title }}</td>
                                   <td>{{ project.updated_at|date:'d/m/Y' }}</td>
                                   <td class="text-right bold">
                                    <a href="{% url 'breakdowns:project_update' project.id %}" class="btn btn-default btn-sm"><span class="fa fa-edit"></span> Edit</a>
                                   </td>
                               </tr>
                               {% endfor %}

                           </tbody>
                       </table>
                   </div><!-- /END .table-responsive -->
                   {% else %}
                   <p class="text-center breath-both-lg text-fade"><strong><span class="fa fa-exclamation-circle"></span> You currently have no project</strong></p>
                   {% endif %}
                </div>
                <div class="panel-footer">
                    <a href="{% url 'breakdowns:project_create' %}" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Project</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}